species_by_family = { 'sparrow'         : ['aberts towhee', 'american pipit', 'american tree sparrow', 'bairds sparrow', 'bells sparrow', 'black throated sparrow', 'botteris sparrow', 'brewers sparrow', 'california towhee', 'canyon towhee', 'cassins sparrow', 'chestnut collared longspur', 'chipping sparrow', 'clay colored sparrow', 'dark eyed junco', 'dickcissel', 'eastern towhee', 'eurasion tree sparrow', 'field sparrow', 'fox sparrow', 'golden crowned sparrow', 'grasshopper sparrow', 'green tailed towhee', 'harris sparrow', 'henslows sparrow', 'horned lark', 'house sparrow', 'lapland longspur', 'lark bunting', 'lark sparrow', 'lecontes sparrow', 'lincolns sparrow', 'mccowns longspur', 'nelsons sparrow', 'rufous crowned sparrow', 'rufous winged sparrow', 'sagebrush sparrow' , 'saltmarsh sparrow', 'savannah sparrow', 'seaside sparrow', 'smiths longspur', 'snow bunting', 'song sparrow', 'spotted towhee', 'spragues pipit', 'swamp sparrow', 'vesper sparrow', 'white crowned sparrow', 'white throated sparrow']
                     ,'finch'           : ['american goldfinch', 'black headed grosbeak', 'black rosy finch', 'blue grosbeak', 'brown capped rosy finch', 'cassia crossbill', 'cassins finch', 'common redpoll', 'evening grosbeak', 'gray crowned rosy finch', 'hepatic tanager', 'hoary redpoll', 'house finch', 'indigo bunting', 'lawrences goldfinch', 'lazuli bunting', 'lesser goldfinch', 'northern cardinal', 'painted bunting', 'pine grosbeak', 'pine siskin', 'purple finch', 'pyrrhuloxia', 'red crossbill', 'rose breasted grosbeak', 'scarlet tanager', 'summer tanager', 'varied bunting', 'western tanager', 'white winged crossbill']
                     ,'hummingbird'     : ['allens hummingbird', 'annas hummingbird', 'black chinned hummingbird', 'blue throated hummingbird', 'broad billed hummingbird', 'broad tailed hummingbird', 'buff bellied hummingbird', 'calliope hummingbird', 'costas hummingbird', 'lucifer hummingbird', 'rivolis hummingbird', 'ruby throated hummingbird', 'rufous hummingbird']
                     ,'warbler'         : ['american redstart', 'arctic warbler', 'bay breasted warbler', 'bells vireo', 'black and white warbler', 'blackburnian warbler', 'black capped vireo', 'blackpoll warbler', 'black throated blue warbler', 'black throated gray warbler', 'black throated green warbler', 'black whiskered vireo', 'blue headed vireo', 'blue winged warbler', 'canada warbler', 'cape may warbler', 'cassins vireo', 'cerulean warbler', 'chestnut sided warbler', 'common yellowthroat', 'connecticut warbler', 'golden cheeked warbler', 'golden winged warbler', 'graces warbler', 'gray vireo', 'hermit warbler', 'hooded warbler', 'huttons vireo', 'kentucky warbler', 'kirtlands warbler', 'louisiana waterthrush', 'lucys warbler', 'macgillivrays warbler', 'magnolia warbler', 'mourning warbler', 'nashville warbler', 'northern parula', 'northern waterthrush', 'orange crowned warbler', 'ovenbird', 'painted redstart', 'palm warbler', 'philadelphia vireo', 'pine warbler', 'plumbeous vireo', 'prairie warbler', 'prothonotary warbler', 'red eyed vireo', 'red faced warbler', 'swainsons warbler', 'tennessee warbler', 'townsends warbler', 'virginias warbler', 'warbling vireo', 'white eyed vireo', 'wilsons warbler', 'worm eating warbler', 'yellow breasted chat', 'yellow rumped warbler', 'yellow throated vireo', 'yellow throated warbler', 'yellow warbler']
                     ,'chickadee'       : ['black capped chickadee', 'black crested titmouse', 'black tailed gnatcatcher', 'blue gray gnatcatcher', 'boreal chickadee', 'bridled titmouse', 'bushtit', 'carolina chickadee', 'chestnut backed chickadee', 'golden crowned kinglet', 'juniper titmouse', 'mountain chickadee', 'oak titmouse', 'ruby crowned kinglet', 'tufted titmouse', 'verdin', 'wrentit']
                     ,'auk'             : ['ancient murrelet', 'atlantic puffin', 'black guillemot', 'cassins auklet', 'common murre', 'dovekie', 'horned puffin', 'marbled murrelet', 'parakeet auklet', 'pigeon guillemot', 'razorbill', 'rhinoceros auklet', 'thick billed murre', 'tufted puffin']
                     ,'blackbird'       : ['altamira oriole', 'audubons oriole', 'baltimore oriole', 'boat tailed grackle', 'bobolink', 'brewers blackbird', 'bronzed cowbird', 'brown headed cowbird', 'bullocks oriole', 'common grackle', 'eastern meadowlark', 'european starling', 'great tailed grackle', 'hooded oriole', 'orchard oriole', 'red winged blackbird', 'rusty blackbird', 'scotts oriole', 'shiny cowbird', 'spot breasted oriole', 'tricolored blackbird', 'western meadowlark', 'yellow headed blackbird']
                     ,'crow'            : ['american crow', 'black billed magpie', 'chihuahuan raven', 'common raven', 'fish crow', 'northwestern crow', 'yellow billed magpie']
                     ,'dove'            : ['african collared dove', 'band tailed pigeon', 'common ground dove', 'eurasian collared dove', 'inca dove', 'mourning dove', 'rock pigeon', 'white crowned pigeon', 'white tipped dove', 'white winged dove']
                     ,'duck'            : ['american black duck', 'american coot', 'american wigeon', 'barrows goldeneye', 'black bellied whistling duck', 'black scoter', 'blue winged teal', 'brant', 'bufflehead', 'cackling goose', 'canada goose', 'canvasback', 'cinnamon teal', 'clarks grebe', 'common eider', 'common gallinule', 'common goldeneye', 'common loon', 'common merganser', 'eared grebe', 'emperor goose', 'eurasian wigeon', 'fulvous whistling duck', 'gadwall', 'greater scaup', 'greater white fronted goose', 'green winged teal', 'harlequin duck', 'hooded merganser', 'horned grebe', 'king eider', 'least grebe', 'lesser scaup', 'long tailed duck', 'mallard', 'mottled duck', 'muscovy duck', 'mute swan', 'northern pintail', 'northern shoveler', 'pacific loon', 'pied billed grebe', 'purple gallinule', 'red breasted merganser', 'redhead', 'red necked grebe', 'red throated loon', 'ring necked duck', 'ross goose', 'ruddy duck', 'snow goose', 'stellers eider', 'surf scoter', 'trumpeter swan', 'tundra swan', 'western grebe', 'white winged scoter', 'wood duck']
                     ,'falcon'          : ['american kestrel', 'crested caracara', 'gyrfalcon', 'merlin', 'peregrine falcon', 'prairie falcon']
                     ,'flycatcher'      : ['acadian flycatcher', 'alder flycatcher', 'ash throated flycatcher', 'black phoebe', 'bohemian waxwing', 'buff breasted flycatcher', 'cassins kingbird', 'cedar waxwing', 'cordilleran flycatcher', 'couchs kingbird', 'dusky flycatcher', 'eastern kingbird', 'eastern phoebe', 'eastern wood pewee', 'elegant trogon', 'gray flycatcher', 'great crested flycatcher', 'greater pewee', 'great kiskadee', 'hammonds flycatcher', 'least flycatcher', 'loggerhead shrike', 'northern shrike', 'olive sided flycatcher', 'pacific slope flycatcher', 'phainopepla', 'says phoebe', 'scissor tailed flycatcher', 'tropical kingbird', 'vermilion flycatcher', 'western kingbird', 'western wood pewee', 'willow flycatcher', 'yellow bellied flycatcher']
                     ,'game bird'       : ['california quail', 'chukar', 'dusky grouse', 'gambels quail', 'gray partridge', 'greater prairie chicken', 'greater sage grouse', 'gunnison sage grouse', 'lesser prairie chicken', 'montezuma quail', 'mountain quail', 'northern bobwhite', 'plain chachalaca', 'ring necked pheasant', 'rock ptarmigan', 'ruffed grouse', 'scaled quail', 'sharp tailed grouse', 'sooty grouse', 'spruce grouse', 'white tailed ptarmigan', 'wild turkey', 'willow ptarmigan']
                     ,'gull'            : ['black headed gull', 'black legged kittiwake', 'bonapartes gull', 'california gull', 'franklins gull', 'glaucous gull', 'glaucous winged gull', 'great black backed gull', 'heermanns gull', 'herring gull', 'iceland gull', 'ivory gull', 'laughing gull', 'lesser black backed gull', 'little gull', 'mew gull', 'ring billed gull', 'ross gull', 'sabines gull', 'western gull']
                     ,'hawk'            : ['bald eagle', 'broad winged hawk', 'coopers hawk', 'ferruginous hawk', 'golden eagle', 'gray hawk', 'harris hawk', 'mississippi kite', 'northern goshawk', 'northern harrier', 'osprey', 'red shouldered hawk', 'red tailed hawk', 'rough legged hawk', 'sharp shinned hawk', 'snail kite', 'swainsons hawk', 'swallow tailed kite', 'white tailed hawk', 'white tailed kite', 'zone tailed hawk']
                     ,'heron'           : ['american bittern', 'black crowned night heron', 'cattle egret', 'glossy ibis', 'great blue heron', 'great egret', 'green heron', 'least bittern', 'limpkin', 'little blue heron', 'reddish egret', 'roseate spoonbill', 'sandhill crane', 'snowy egret', 'tricolored heron', 'white faced ibis', 'white ibis', 'whooping crane', 'wood stork', 'yellow crowned night heron']
                     ,'jay'             : ['blue jay', 'california scrub jay', 'clarks nutcracker', 'florida scrub jay', 'gray jay', 'green jay', 'mexican jay', 'pinyon jay', 'stellers jay', 'woodhouses scrub jay']
                     ,'kingfisher'      : ['belted kingfisher']
                     ,'nuthatch'        : ['brown creeper', 'brown headed nuthatch', 'pygmy nuthatch', 'red breasted nuthatch', 'white breasted nuthatch']
                     ,'owl'             : ['barn owl', 'barred owl', 'boreal owl', 'burrowing owl', 'chuck wills widow', 'common nighthawk', 'common pauraque', 'common poorwill', 'eastern screech owl', 'eastern whip poor will', 'flammulated owl', 'great gray owl', 'great horned owl', 'lesser nighthawk', 'long eared owl', 'norther hawk owl', 'northern pygmy owl', 'northern saw whet owl', 'short eared owl', 'snowy owl', 'spotted owl', 'western screech owl']
                     ,'parrot'          : ['monk parakeet']
                     ,'seabird'         : ['american white pelican', 'anhinga', 'black footed albatross', 'blue footed booby', 'brandts cormorant', 'brown booby', 'brown pelican', 'double crested cormorant', 'fork tailed storm petrel', 'great cormorant', 'laysan albatross', 'magnificent frigatebird', 'masked booby', 'neotropic cormorant', 'northern fulmar', 'northern gannet', 'pelagic cormorant', 'red footed booby']
                     ,'shorebird'       : ['american avocet', 'american golden plover', 'american oystercatcher', 'american woodcock', 'bairds sandpiper', 'black bellied plover', 'black necked stilt', 'black oystercatcher', 'black rail', 'black turnstone', 'buff breasted sandpiper', 'clapper rail', 'dunlin', 'greater yellowlegs', 'hudsonian godwit', 'killdeer', 'king rail', 'least sandpiper', 'lesser yellowlegs', 'long billed curlew', 'long billed dowitcher', 'marbled godwit', 'mountain plover', 'pacific golden plover', 'pectoral sandpiper', 'piping plover', 'purple sandpiper', 'red knot', 'ridgways rail', 'rock sandpiper', 'ruddy turnstone', 'sanderling', 'semipalmated plover', 'semipalmated sandpiper', 'short billed dowitcher', 'snowy plover', 'solitary sandpiper', 'sora', 'spotted sandpiper', 'stilt sandpiper', 'surfbird', 'upland sandpiper', 'virginia rail', 'wandering tattler', 'western sandpiper', 'whimbrel', 'white rumped sandpiper', 'willet', 'wilsons phalarope', 'wilsons plover', 'wilsons snipe', 'yellow rail']
                     ,'swallow'         : ['bank swallow', 'barn swallow', 'cave swallow', 'cliff swallow', 'northern rough winged swallow', 'purple martin', 'tree swallow', 'violet green swallow']
                     ,'swift'           : ['chimney swift', 'vauxs swift', 'white throated swift']
                     ,'tern'            : ['arctic tern', 'black skimmer', 'black tern', 'caspian tern', 'common tern', 'elegant tern', 'forsters tern', 'gull billed tern', 'least tern', 'roseate tern', 'royal tern', 'sandwich tern']
                     ,'thrush'          : ['american dipper', 'american robin', 'bendires thrasher', 'bicknells thrush', 'black billed cuckoo', 'bluethroat', 'brown thrasher', 'california thrasher', 'crissal thrasher', 'curved billed thrasher', 'eastern bluebird', 'gray catbird', 'gray cheeked thrush', 'greater roadrunner', 'groove billed ani', 'hermit thrush', 'lecontes thrasher', 'long billed thrasher', 'mangrove cuckoo', 'mountain bluebird', 'northern mockingbird', 'sage thrasher', 'smooth billed ani', 'swainsons thrush', 'townsends solitaire', 'varied thrush', 'veery', 'western bluebird', 'wood thrush', 'yellow bellied cuckoo']
                     ,'vulture'         : ['black vulture', 'california condor', 'turkey vulture']
                     ,'woodpecker'      : ['acord woodpecker', 'american three toed woodpecker', 'arizona woodpecker', 'black backed woodpecker', 'downy woodpecker', 'gila woodpecker', 'gilded flicker', 'golden fronted woodpecker', 'hairy woodpecker', 'ivory billed woodpecker', 'ladder backed woodpecker', 'lewis woodpecker', 'northern flicker', 'nuttalls woodpecker', 'pileated woodpecker', 'red bellied woodpecker', 'red breasted sapsucker', 'red cockaded woodpecker', 'red headed woodpecker', 'red naped sapsucker', 'white headed woodpecker', 'williamsons sapsucker', 'yellow bellied sapsucker']
                     ,'wren'            : ['bewicks wren', 'cactus wren', 'canyon wren', 'carolina wren', 'house wren', 'marsh wren', 'pacific wren', 'rock wren', 'sedge wren', 'winter wren']
                    }

help_message = "```fix\n" \
               "INFO: Creator of this bot is ChairMane: https://github.com/ChairMane/Birdy\n\n" \
               "DESCRIPTION: Birdy is for those discord users who are interested\n" \
               "in birds.\n\n" \
               "COMMAND PREFIX: To be able to use the commands, '<>' must be\n" \
               "present before any commands are used.\n\n" \
               "Below are commands available:\n\n" \
               "__________________________________________________________\n\n" \
               "COMMAND:              <> <shape_of_bird>\n" \
               "EXAMPLES:             <> sparrow\n" \
               "                      <> finch\n" \
               "                      <> warbler\n" \
               "DESCRIPTION: This command gives the user a list of birds within\n" \
               "the shape of bird category. So if you want a list of birds that\n" \
               "have the shape of a sparrow, you input <> sparrow.\n" \
               "__________________________________________________________\n\n" \
               "COMMAND:              <> <name_of_bird>\n" \
               "EXAMPLES:             <> white crowned sparrow\n" \
               "                      <> northern parula\n" \
               "                      <> annas hummingbird\n" \
               "DESCRIPTION: If you know the name of the bird you want,\n" \
               "you can call this command to grab information on it.\n" \
               "__________________________________________________________\n\n" \
               "COMMAND:              <> rand\n" \
               "DESCRIPTION: Use <> rand to grab information on a random\n" \
               "within the Birdy database.\n" \
               "__________________________________________________________\n\n" \
               "COMMAND:              <> rand <shape_of_bird>\n" \
               "EXAMPLES:             <> rand finch\n" \
               "                      <> rand sparrow\n" \
               "DESCRIPTION: If you want a random bird within a specific\n" \
               "bird shape category, you call this command.\n" \
               "__________________________________________________________\n\n" \
               "COMMAND:              <> help\n" \
               "DESCRIPTION: If you forget commands, you can call this\n" \
               "command to get a list of commands.\n" \
               "__________________________________________________________\n\n" \
               "LIST OF CURRENT BIRD SHAPES:\n" \
               "Sparrow, Finch, Warbler, Hummingbird, Auk, Blackbird, Crow, Dove,\n" \
               "Duck, Falcon, Flycatcher, Game Bird, Gull, Hawk, Heron, Jay, Kingfisher,\n" \
               "Nuthatch, Owl, Parrot, Seabird, Shorebird, Swallow, Swift, Tern, Thrush, \n" \
               "Vulture, Woodpecker and Wren.\n" \
               "```"
